--
-------------------------------------------------------------------------------------------------------------------
--
-->Codigo Historico:
--{07} = {tmp_mfj_01_dp_07_a_codigo_historico}
    /*
        07 = {tmp_mfj_01_dp_07_a_codigo_historico}
                {
                    >Codigo Historico:
                        [id_cod_hst] = identificador
                        [cod_empresa] = codigo empresa {padraoBD}
                        [cod_credor] = codigo credor {padraoBD}
                        [id_perfil_cob] = parametrizado para filtro {02=supervisor/cobrador}
                        [cod_hist] = codigo historico {padraoBD}
                        [des_hist] = descricao do codigo historico
                        [cod_acao_cob_flt] = codigo da acao {identificador da acao}
                        [cod_compl] = codigo do hst para cliente {categoria + tipo + complemento}
                        [c01m] = acao 01 {categoria}
                        [c02m] = acao 02 {tipo}
                        [c03m] = acao 03 {complemento}
                        [ocor_p] = ocorrencia considerada positiva {KPI_hst}
                        [acio] = acionamento considerado {KPI_hst}
                        [alo] = alo, alguem atendeu {KPI_hst}
                        [cpc] = cpc, contato com a pessoa certa {KPI_hst}
                        [opac] = oportunidade de acordo {KPI_hst}
                        [ac] = proposta formalizada {KPI_hst}
                        [badcall] = ligacao caiu {KPI_hst}
                        [hang_up] = queda na transferencia de ligacao atendida (indisponibilidade de ramal) {KPI_hst}
                        [tel_inv] = telefone invalido {KPI_hst}
                }><m
    */
--
--SELECT * FROM public.tmp_mfj_01_dp_07_a_codigo_historico;
--
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (1,1,6,2,5,'ATIVO - Boleto enviado via Whatsapp',10,'NOVO  ','MM','NO','VO',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (2,1,6,2,7,'RECEPTIVO - Cliente envia comprovante de pagamento via Whats',10,'NOVO  ','MM','NO','VO',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (3,1,6,2,20,'RECEPTIVO - Alega pagamento',12,'REHHHH','RE','HH','HH',1,1,1,1,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (4,1,6,2,60,'ATIVO - Recado',1,'TEAAAA','TE','AA','AA',1,1,1,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (5,1,6,2,140,'ATIVO - Formalizado acordo',1,'TEFFFD','TE','FF','FD',1,1,1,1,0,1,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (6,1,6,2,200,'ATIVO - Cliente não localizado',1,'TEBBBD','TE','BB','BD',1,1,1,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (7,1,6,2,210,'ATIVO - Telefone nao atende',1,'TECCCA','TE','CC','CA',1,1,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (8,1,6,2,220,'RECEPTIVO - Retorno SMS',12,'RESMZZ','RE','SM','ZZ',1,1,1,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (9,1,6,2,260,'RECEPTIVO - Cliente falecido',12,'REBBBG','RE','BB','BG',1,1,1,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (10,1,6,2,390,'ATIVO - Cliente falecido',1,'TEBBBG','TE','BB','BG',1,1,1,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (11,1,6,2,501,'ATIVO - Alega pagamento',1,'TEHHHH','TE','HH','HH',1,1,1,1,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (12,1,6,2,510,'ATIVO - SMS ENVIADO:',7,'SMZZZZ','SM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (13,1,6,2,580,'RECEPTIVO - Formalizado acordo',12,'REFFFD','RE','FF','FD',1,1,1,1,0,1,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (14,1,6,0,650,'DISCADOR - ANUNCIADORA',15,'FLCCCB','FL','CC','CB',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (15,1,6,0,660,'DISCADOR - NÃO ATENDE',15,'FLCCCA','FL','CC','CA',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (16,1,6,0,670,'DISCADOR - SILENCIO',15,'FLCCZZ','FL','CC','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (17,1,6,0,680,'DISCADOR - DISCAGEM CANCELADA',15,'FLCCCB','FL','CC','CB',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (18,1,6,0,690,'DISCADOR - MSG OPERADORA',15,'FLCCCB','FL','CC','CB',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (19,1,6,0,700,'DISCADOR - FALHA OPERADORA',15,'FLCCCB','FL','CC','CB',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (20,1,6,0,710,'DISCADOR - NRO INVALIDO',15,'FLCCCB','FL','CC','CB',0,0,0,0,0,0,0,0,1);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (21,1,6,0,720,'DISCADOR - OCUPADO',15,'FLCCCA','FL','CC','CA',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (22,1,6,0,721,'DISCADOR - CONGESTIONAMENTO INTERNO',15,'FLCCCA','FL','CC','CA',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (23,1,6,0,730,'DISCADOR - No Disposition',1,'TECCCB','TE','CC','CB',1,1,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (24,1,6,0,740,'DISCADOR - FAX',1,'TECCCB','TE','CC','CB',1,1,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (25,1,6,0,750,'DISCADOR - HANGUP',1,'TECHCE','TE','CH','CE',1,0,0,0,0,0,0,1,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (26,1,6,2,999,'ATIVO - Não Atende - Interesse',1,'TECCCA','TE','CC','CA',1,1,0,0,1,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (27,1,6,2,5000,'ATIVO - TELEFONE NÃO PERTENCE AO CLIENTE',1,'TEBBBD','TE','BB','BD',1,1,1,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (28,1,6,2,5001,'ATIVO - Caixa postal',1,'TECCCA','TE','CC','CA',1,1,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (29,1,6,2,5002,'ATIVO - Telefone não existe / não completa',1,'TECCCB','TE','CC','CB',1,1,0,0,0,0,0,0,1);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (30,1,6,2,5003,'RECEPTIVO - Telefone não pertence ao cliente',12,'REBBBD','RE','BB','BD',1,1,1,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (31,1,6,2,5005,'DISCADOR - LIGACAO CAIU',1,'TEMMMA','TE','MM','MA',1,1,0,0,0,0,1,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (32,1,6,2,5006,'DISCADOR - TRANSFERENCIA DE LIGACAO MUDA',1,'TECCZZ','TE','CC','ZZ',1,1,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (33,1,6,0,5555,'A02364',7,'SMZZZZ','SM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (34,1,6,0,5556,'A02369',8,'EMZZZZ','EM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (35,1,6,0,5557,'A02362',7,'SMZZZZ','SM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (36,1,6,0,5558,'A02363',7,'SMZZZZ','SM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (37,1,6,2,5559,'A02365',7,'SMZZZZ','SM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (38,1,6,0,5560,'A02366',7,'SMZZZZ','SM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (39,1,6,0,5561,'A02367',7,'SMZZZZ','SM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (40,1,6,0,6002,'A003307',7,'SMZZZZ','SM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (41,1,6,2,6003,'A003308',7,'SMZZZZ','SM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (42,1,6,0,6004,'A003309',7,'SMZZZZ','SM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (43,1,6,0,6005,'A003306',8,'EMZZZZ','EM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (44,1,6,2,7001,'ATIVO - PROMESSA DE PG FORA DA ALÇADA:',1,'TEAAAL','TE','AA','AL',1,1,1,1,1,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (45,1,6,2,7002,'RECEPTIVO - PROMESSA DE PG FORA DA ALÇADA:',12,'REAAAL','RE','AA','AL',1,1,1,1,1,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (46,1,6,2,7003,'ATIVO - PROMESSA DE PAGAMENTO PARA:',1,'TEAAAL','TE','AA','AL',1,1,1,1,1,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (47,1,6,2,7004,'RECEPTIVO - PROMESSA DE PAGAMENTO PARA:',12,'REAAAL','RE','AA','AL',1,1,1,1,1,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (48,1,6,2,7005,'ATIVO - Solicitou retorno:',1,'TEAAAM','TE','AA','AM',1,1,1,1,1,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (49,1,6,2,7006,'RECEPTIVO - Solicitou retorno:',1,'TEAAAM','TE','AA','AM',1,1,1,1,1,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (50,1,6,2,7007,'ATIVO - Sem contato no dia',1,'TECCCA','TE','CC','CA',1,1,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (51,1,6,2,7008,'RECEPTIVO - Sem acordo',12,'REAAAG','RE','AA','AG',1,1,1,1,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (52,1,6,2,7009,'ATIVO - Sem acordo',1,'TEAAAG','TE','AA','AG',1,1,1,1,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (53,1,6,2,8450,'RECEPTIVO  - Preventivo boleto',12,'REAAAL','RE','AA','AL',1,1,1,1,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (54,1,6,2,8451,'RECEPTIVO  - Preventivo pagamento',12,'REAAAL','RE','AA','AL',1,1,1,1,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (55,1,6,2,8452,'ATIVO - Preventivo boleto',1,'TEAAAL','TE','AA','AL',1,1,1,1,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (56,1,6,2,8453,'ATIVO  - Preventivo Pagamento',1,'TEAAAL','TE','AA','AL',1,1,1,1,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (57,1,950,2,20,'RECEPTIVO - Alega pagamento',12,'REHHHH','RE','HH','HH',1,1,1,1,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (58,1,950,2,60,'ATIVO - Recado',1,'TEAAAA','TE','AA','AA',1,1,1,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (59,1,950,2,140,'ATIVO - Formalizado acordo',1,'TEFFFD','TE','FF','FD',1,1,1,1,0,1,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (60,1,950,2,200,'ATIVO - Cliente não localizado',1,'TEBBBD','TE','BB','BD',1,1,1,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (61,1,950,2,210,'ATIVO - Telefone nao atende',1,'TECCCA','TE','CC','CA',1,1,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (62,1,950,2,220,'RECEPTIVO - Retorno SMS',12,'RESMZZ','RE','SM','ZZ',1,1,1,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (63,1,950,2,260,'RECEPTIVO - Cliente falecido',12,'REBBBG','RE','BB','BG',1,1,1,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (64,1,950,2,390,'ATIVO - Cliente falecido',1,'TEBBBG','TE','BB','BG',1,1,1,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (65,1,950,2,501,'ATIVO - Alega pagamento',1,'TEHHHH','TE','HH','HH',1,1,1,1,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (66,1,950,2,510,'ATIVO - SMS ENVIADO:',7,'SMZZZZ','SM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (67,1,950,2,580,'RECEPTIVO - Formalizado acordo',12,'REFFFD','RE','FF','FD',1,1,1,1,0,1,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (68,1,950,2,650,'DISCADOR - ANUNCIADORA',15,'FLCCCB','FL','CC','CB',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (69,1,950,0,660,'DISCADOR - NÃO ATENDE',15,'FLCCCA','FL','CC','CA',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (70,1,950,0,670,'DISCADOR - SILENCIO',15,'FLCCZZ','FL','CC','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (71,1,950,0,680,'DISCADOR - DISCAGEM CANCELADA',15,'FLCCCB','FL','CC','CB',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (72,1,950,0,690,'DISCADOR - MSG OPERADORA',15,'FLCCCB','FL','CC','CB',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (73,1,950,0,700,'DISCADOR - FALHA OPERADORA',15,'FLCCCB','FL','CC','CB',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (74,1,950,0,710,'DISCADOR - NRO INVALIDO',15,'FLCCCB','FL','CC','CB',0,0,0,0,0,0,0,0,1);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (75,1,950,0,720,'DISCADOR - OCUPADO',15,'FLCCCA','FL','CC','CA',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (76,1,950,0,721,'DISCADOR - CONGESTIONAMENTO INTERNO',15,'FLCCCA','FL','CC','CA',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (77,1,950,0,730,'DISCADOR - NoDisposition',1,'TECCCB','TE','CC','CB',1,1,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (78,1,950,0,740,'DISCADOR - FAX',1,'TECCCB','TE','CC','CB',1,1,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (79,1,950,0,750,'DISCADOR - HANGUP',1,'TECHCE','TE','CH','CE',1,0,0,0,0,0,0,1,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (80,1,950,2,999,'ATIVO - Não Atende - Interesse',1,'TECCCA','TE','CC','CA',1,1,0,0,1,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (81,1,950,2,1000,'DISCADOR - TRANSFERÊNCIA DE LIGAÇÃO MUDA',1,'TECCZZ','TE','CC','ZZ',1,1,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (82,1,950,2,1001,'ATIVO - TELEFONE NÃO PERTENCE AO CLIENTE',1,'TEBBBD','TE','BB','BD',1,1,1,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (83,1,950,2,1500,'DISCADOR - LIGAÇÃO CAIU',1,'TEMMMA','TE','MM','MA',1,1,0,0,0,0,1,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (84,1,950,2,5000,'ATIVO - TELEFONE NÃO PERTENCE AO CLIENTE',1,'TEBBBD','TE','BB','BD',1,1,1,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (85,1,950,2,5001,'ATIVO - Caixa postal',1,'TECCCA','TE','CC','CA',1,1,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (86,1,950,2,5002,'ATIVO - Telefone não existe / não completa',1,'TECCCB','TE','CC','CB',1,1,0,0,0,0,0,0,1);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (87,1,950,2,5003,'RECEPTIVO - Telefone não pertence ao cliente',12,'REBBBD','RE','BB','BD',1,1,1,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (88,1,950,2,5005,'DISCADOR - LIGACAO CAIU',1,'TEMMMA','TE','MM','MA',1,1,0,0,0,0,1,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (89,1,950,2,5006,'DISCADOR - TRANSFERENCIA DE LIGACAO MUDA',1,'TECCZZ','TE','CC','ZZ',1,1,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (90,1,950,0,5555,'A02372',7,'SMZZZZ','SM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (91,1,950,0,5556,'A02370',8,'EMZZZZ','EM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (92,1,950,0,5557,'A02371',7,'SMZZZZ','SM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (93,1,950,0,5558,'A02374',7,'SMZZZZ','SM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (94,1,950,0,5559,'A02375',7,'SMZZZZ','SM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (95,1,950,0,5560,'A02376',7,'SMZZZZ','SM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (96,1,950,0,5561,'A02373',7,'SMZZZZ','SM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (97,1,950,0,6002,'A003307',7,'SMZZZZ','SM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (98,1,950,2,6003,'A003308',7,'SMZZZZ','SM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (99,1,950,0,6004,'A003309',7,'SMZZZZ','SM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (100,1,950,0,6005,'A003306',8,'EMZZZZ','EM','ZZ','ZZ',0,0,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (101,1,950,2,7000,'ATIVO - Telefone não existe / não completa',1,'TECCCB','TE','CC','CB',1,1,0,0,0,0,0,0,1);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (102,1,950,2,7001,'ATIVO - PROMESSA DE PG FORA DA ALÇADA:',1,'TEAAAL','TE','AA','AL',1,1,1,1,1,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (103,1,950,2,7002,'RECEPTIVO - PROMESSA DE PG FORA DA ALÇADA:',12,'REAAAL','RE','AA','AL',1,1,1,1,1,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (104,1,950,2,7003,'ATIVO - PROMESSA DE PAGAMENTO PARA:',1,'TEAAAL','TE','AA','AL',1,1,1,1,1,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (105,1,950,2,7004,'RECEPTIVO - PROMESSA DE PAGAMENTO PARA:',12,'REAAAL','RE','AA','AL',1,1,1,1,1,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (106,1,950,2,7005,'RECEPTIVO - Solicitou retorno:',1,'TEAAAM','TE','AA','AM',1,1,1,1,1,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (107,1,950,2,7006,'ATIVO - Solicitou retorno:',1,'TEAAAM','TE','AA','AM',1,1,1,1,1,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (108,1,950,2,7007,'ATIVO - Sem contato no dia',1,'TECCCA','TE','CC','CA',1,1,0,0,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (109,1,950,2,7008,'RECEPTIVO - Sem acordo',12,'REAAAG','RE','AA','AG',1,1,1,1,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (110,1,950,2,7009,'ATIVO - Sem acordo',1,'TEAAAG','TE','AA','AG',1,1,1,1,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (111,1,950,2,8450,'RECEPTIVO  - Preventivo boleto',12,'REAAAL','RE','AA','AL',1,1,1,1,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (112,1,950,2,8451,'RECEPTIVO  - Preventivo pagamento',12,'REAAAL','RE','AA','AL',1,1,1,1,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (113,1,950,2,8452,'ATIVO - Preventivo boleto',1,'TEAAAL','TE','AA','AL',1,1,1,1,0,0,0,0,0);
INSERT INTO public.tmp_mfj_01_dp_07_a_codigo_historico (id_cod_hst,cod_empresa,cod_credor,id_perfil_cob,cod_hist,des_hist,cod_acao_cob_flt,cod_compl,c01m,c02m,c03m,ocor_p,acio,alo,cpc,opac,ac,badcall,hang_up,tel_inv) VALUES (114,1,950,2,8453,'ATIVO  - Preventivo Pagamento',1,'TEAAAL','TE','AA','AL',1,1,1,1,0,0,0,0,0);
--
-------------------------------------------------------------------------------------------------------------------
--